export default function RoleSpecPanel({ rolespec }: { rolespec: any }) {
  if (!rolespec) return <div className="ivory-panel">No RoleSpec available yet.</div>;
  const weights = Object.entries(rolespec.scoring_weights || {}).sort((a: any, b: any) => b[1] - a[1]);
  return (
    <section className="rolespec-grid">
      <div className="ivory-panel">
        <span className="eyebrow">Active policy</span>
        <h2>{rolespec.role_title}</h2>
        <p>{rolespec.role_family} / {rolespec.target_seniority}</p>
        {rolespec._talentrank && (
          <div className="rolespec-source">
            <strong>{sourceLabel(rolespec._talentrank.source)}</strong>
            {rolespec._talentrank.cache_key && <span>Cache key {rolespec._talentrank.cache_key}</span>}
          </div>
        )}
        <h3>Competency weights</h3>
        {weights.map(([name, value]: any) => (
          <div className="weight-row" key={name}>
            <span>{name.replaceAll("_", " ")}</span>
            <strong>{Number(value).toFixed(2)}</strong>
          </div>
        ))}
      </div>
      <div className="dark-panel">
        <h3>Evidence requirements</h3>
        {(rolespec.evidence_requirements || []).map((item: any) => (
          <p key={item.name}>{item.name}: min {item.min_score} from {(item.required_sources || []).join(", ") || "any source"}</p>
        ))}
        <h3>Score caps</h3>
        {(rolespec.score_caps || []).map((item: any) => (
          <p key={item.rule}>{item.rule}: max {item.max_score}</p>
        ))}
      </div>
    </section>
  );
}

function sourceLabel(source: string) {
  if (source === "llm_cache") return "Reused cached LLM RoleSpec";
  if (source === "llm_generated") return "Generated by LLM and cached";
  if (source === "uploaded_rolespec") return "Uploaded RoleSpec";
  if (source === "saved_redrob") return "Saved Redrob RoleSpec";
  return "Validated RoleSpec";
}
